### ISSUE TITLE
FR: include unzip

### ISSUE THREAD

**Issue by samip5** [siderolabs/tools#394]
It seems that this would be beneficial to have for decompressing of archives, but for a reason unknown to me, it's not included?

The checksum validation with the release .tar.gz uses a different checksum everytime one downloads using that, which is confusing, so this would help with that as the release usually has an zip included if not anything else.

**Comment by smira** [comment]
I don't know many modern projects which would use zip nowadays (around Unix/Linux).

`.tar` archives are way more popular, and when it comes to GitHub automatic archives from tags they are mostly good, and zip certainly won't help.
